### PR TITLE
Bump scala, sbt and libs

### PR DESCRIPTION
**Pull request by carlosedp**

### CODE REVIEW

**Comment by carlosedp** [comment]
I don't get why node-fetch is defined on both build.sbt and package.json specially with different versions.

I removed locally the one from build.sbt and the dev version worked fine.

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
Thanks !

**Comment by carlosedp** [comment]
Sweet! Can you cut a new version with both PRs?
Thanks a lot!!

**Comment by Baccata** [comment]
Will do today

**Pull request merged**
